version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wp}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wp}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${DB_USER:-wp}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wp}
      WP_HOME: http://localhost:8080
      WP_SITEURL: http://localhost:8080
    ports:
      - "8080:80"
    volumes:
      - ..:/workspace
      - wp_data:/var/www/html
      - ../wp-content:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "9090:80"

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data:
  wp_data:
